### ISSUE TITLE
Brackets inside comments and string literals

### ISSUE THREAD

**Issue by Eugenii10** [Gruntfuggly/scoper#3]
Brackets inside comments and string literals are wrongly treated as scope borders. It leads to unpredictable scope definition inside the document.

### Summary
VS Code: 1.20.1
Scoper: 0.0.5
OS: Windows 7 and 10

## Actual
![ezgif com-optimize](https://user-images.githubusercontent.com/26702097/36972846-712a4a30-20bc-11e8-9e01-483bdbce104a.gif)

## Expected
Brackets inside comments and string literals shouldn't be treated as scope borders.

**Comment by Gruntfuggly** [comment]
Unfortunately, I think this is beyond the scope (sorry) of the extension. It uses a fairly basic search for the brackets backwards and forwards from the cursor position. In order to avoid the problem you have found, it would need to know whether or not a bracket was inside a string, which in itself is problematic due to escaping quotes, etc. Because strings use the same character at both ends, it's much harder to tell.

However, I'll see if I can make a modification...
